services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: egs-frontend-server
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: egs-frontend-client
    ports:
      - "3015:80"
