FROM python:3.8
WORKDIR /app

COPY server/requirements.txt server/api.py server/.flaskenv ./
RUN pip install -r ./requirements.txt
ENV FLAK_ENV production

EXPOSE 5000
CMD [ "gunicorn", "-b", ":5000", "api:app" ]

