
# Create App deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: information-service
  namespace: egs4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: information-service
  template:
    metadata:
      labels:
        app: information-service
    spec:
      containers:
      - name: information-service
        image: registry.deti:5000/information-service:v38
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: information-service-secret
            mountPath: "/tmp/secrets"
            readOnly: true
      volumes:
        - name: information-service-secret
          secret:
            secretName: information-service-secret

# Create Service for APP
---
apiVersion: v1
kind: Service
metadata:
  name: information-service
  namespace: egs4
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: information-service

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: information-service
  namespace: egs4
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: information-service
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: information-service
            port: 
              number: 80