apiVersion: v1
kind: Secret
metadata:
  name: information-service-secret
  namespace: zedleague
stringData:
  API_KEY: ASDzxcdwekjkads786zxc123asdzxc98788ASd9231sz76238
  host: information-service-db
  user: root
  password: root
  dbport: "3306"
  port: "3306"
  database: url_db