# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: information_service_mysql
  labels:
    app: information_service_mysql
spec:
  ports:
  - name: information_service_mysql
    port: 3306
  clusterIP: None
  selector:
    app: information_service_mysql
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the primary: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: information_service_mysql-read
  labels:
    app: information_service_mysql
spec:
  ports:
  - name: information_service_mysql
    port: 3306
  selector:
    app: information_service_mysql