apiVersion: v1
kind: PersistentVolume
metadata:
  name: information-service-mysql-volume
  namespace: zedleague
  labels:
    type: local
spec:
  capacity:
    storage: 50M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: information-service-mysql-claim
  namespace: zedleague
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
