POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "bodas1234a",
    "email": "waa@aw.com",
    "password": "1233456a"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{                                     
    "email": "waa@aw.com",
    "password": "1233456a"

}

###

POST http://localhost:3000/verifyToken
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mjc5NDdiNGU2MjQ1MDRmMDMwZjNkZTkiLCJpYXQiOjE2NTIxODY1NjMsImV4cCI6MTY1MjIwODE2M30.5Nn_LgdVlg1VpzaZ6ogNkX7wN5uSKkXaCUebabacfLs
