FROM node:18

# Create app directory
RUN mkdir /src
WORKDIR /src


# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./src/package.json ./src/package-lock.json ./
COPY ./src/index.js ./src/validation.js ./src/routes/ ./src/node_modules/ ./src/model/ ./src/views/ ./src/.env ./src/

RUN npm install
   
# If you are building your code for production
# RUN npm ci --only=production

COPY ./src .

CMD npm start