swagger: "2.0"
info:
  description: "This service provides the handling of generic notifications."
  version: "0.3"
  title: "Notification Service"

host: "host"
basePath: "/api/v1"

tags:
  - name: "notification"
    description: "Handle Notifications"

schemes:
  - "https"

paths:

  /:
    get:
      tags:
        - "notification"
      summary: "Socket.io endpoint"
      operationId: "receiveNotification"
      produces:
        - "application/json"
      responses:
        "400":
          description: "Invalid uid"

  /notification:
    post:
      tags:
        - "notification"
      summary: ""
      description: ""
      operationId: "sendNotification"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/Notification"
      responses:
        "400":
          description: "Invalid uid"

  /notifications:
    get:
      security:
        - ApiKeyAuth: [ ]
      tags:
        - "notification"
      summary: "User's notification log (persisted notifications)"
      description: "Returns the user's notification log,the results can be paginated (off by default) by sending a PaginationOptions"
      operationId: "getNotifications"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Pagination options (Sending an Options schema enables it)"
          required: false
          schema:
            $ref: "#/definitions/PaginationOptions"
      responses:
        "200":
          description: "User's notifications"
          schema:
            type: object
            properties:
              uid:
                type: "integer"
                description: "User's ID."
              pid:
                type: "integer"
                default: -1
                description: "Id given to the notification when is sent with persist=true. Equal between normal and push notification."
              txt:
                type: "string"
                description: "Notification's content."

        "401":
          description: Authorization information is missing or invalid.

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: Authorization

definitions:
  NotificationOptions:
    type: "object"
    properties:
      email:
        type: "string"
      number:
        type: "integer"
      persist:
        type: "boolean"
        default: false

  Notification:
    type: "object"
    required:
      - text
      - uid
    properties:
      text:
        type: "string"
      uid:
        type: "integer"
      options:
        $ref: "#/definitions/NotificationOptions"

  PaginationOptions:
    type: "object"
    required:
      - nrPages
      - resultsPerPage
    properties:
      nrPages:
        type: "integer"
        minimum: 1
      resultsPerPage:
        type: "integer"
        minimum: 1


