# sudo docker-compose -f deploy/docker-compose.yml  up --build
# sudo docker-compose -f deploy/docker-compose.yml  up

version: "3"
services:
    api:
        container_name: api
        links:
            - db
        image: api
        build:
          context: ..
          dockerfile: deploy/Dockerfile
        ports:
            - "8080:8080"
    db:
        container_name: db
        image: mysql:8.0.21
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ../app/db/entry:/docker-entrypoint-initdb.d/:ro
            - ../app/db/data:/var/lib/mysql
    # app:
    #     container_name: requests
    #     links:
    #         -db
    #     image: api
    #     build:
    #         context: ..
    #         dockerfile: deployRequest/Dockerfile