apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-service-app-jfs-pvc
  namespace: egs4
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50M

---
